name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        bash build.sh

    - name: Push
      uses: actions/upload-artifact@v4
      with:
        name: live-image-amd64.hybrid.iso
        path: live-image-amd64.hybrid.iso
        compression-level: 9
